version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/app
    command: /bin/sh -c "/app/initialize_db.sh && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    environment:
      LOG_LEVEL: debug
      DB_HOST: db
      DB_PORT: 5432
      POSTGRES_DB: demo
      POSTGRES_USER: demouser
      POSTGRES_PASSWORD: password

    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - app-network

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: demouser
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:

volumes:
  postgres_data:
