version: '3.8'

services:
  app:
    build:
      context: .
      args:
        mode: dev
    volumes:
      - .:/app
    command: uvicorn main:app --reload
    environment:
      LOG_LEVEL: debug
    ports:
      - "8000:8000"

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: demouser
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
